// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btgxfhvkvnhhcfcvkjvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0Z3hmaHZrdm5oaGNmY3ZranZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjIyNDcsImV4cCI6MjA2MDg5ODI0N30.hdq2ujfXlRIVyXzy3Bwx9Xdru99-iN5vbdYq-xwLC5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);